services:
  jekyll:
    build: .
    command: jekyll serve --watch --host 0.0.0.0 --port 4000
    ports:
      - "5001:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/index.html"]
      interval: 5s
      timeout: 3s
      retries: 12